[build]
  command = "npm run build"
  # Angular outputs the SPA to the "browser" subfolder when using SSR/static output
  publish = "dist/home-decor-v19/browser"
  functions = "netlify/functions"

# SPA fallback so client-side routes resolve to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 4200

[functions]
  node_bundler = "esbuild"
