[build]
  command = "npm run build"
  publish = "dist/home-decor-v19"
  functions = "netlify/functions"

[dev]
  command = "npm start"
  port = 8888         # Netlify Dev proxy server
  targetPort = 4200   # Angular dev server used by `npm start`

[functions]
  node_bundler = "esbuild"
