[build]
  command = "npm run build"
  # Angular's application builder outputs to a nested "browser" directory
  # e.g. dist/home-decor-v19/browser
  publish = "dist/home-decor-v19/browser"
  functions = "netlify/functions"

[dev]
  command = "npm start"
  port = 8888         # Netlify Dev proxy server
  targetPort = 4200   # Angular dev server used by `npm start`

[functions]
  node_bundler = "esbuild"
